### ISSUE TITLE
Application doesn't load / Missing external resources

### ISSUE THREAD

**Issue by hubert3** [neo4j-examples/movies-python-bolt#12]
Running movies.py and requesting http://127.0.0.1:8080 results in a blank page in Chrome

At least 2 external resources are 404:

http://neo4j-documentation.github.io/developer-resources/language-guides/assets/css/main.css.github.io/developer-resources/language-guides/assets/css/main.css

https://neo4j-contrib.github.io/developer-resources/language-guides/assets/img/logo-white.svg

**Comment by jexp** [comment]
Sorry, I thought I had fixed them already. I pushed another fix, could you try again?

**Comment by hubert3** [comment]
Working now, thanks
