### ISSUE TITLE
issue pip install -r requirements.txt

### ISSUE THREAD

**Issue by Antwnina** [neo4j-examples/movies-python-bolt#2]
Hello, I downloaded the zip file and after i entered these commands $ virtualenv neo4jrestclient-movies
$ source neo4jrestclient-movies/bin/activate which created a new folder in home, where i saved the unziped folder of movies, then i tried to run it by pip as below, and there's error. 
(neo4jrestclient-movies) antonina@antonina-HP-Pavilion-g6-Notebook-PC:~$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by jexp** [comment]
You forgot to enter the directory, please try again with the updated instructions in the readme.
