### ISSUE TITLE
ImportError: cannot import name 'ResultError'

### ISSUE THREAD

**Issue by Northshoot** [neo4j-examples/movies-python-bolt#4]
has this been deprecated?

```
>>> from neo4j.v1 import GraphDatabase, basic_auth, ResultError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ResultError'
```

**Comment by chavan-vjti** [comment]
I am too having the same issue as above.
Kindly, resolve.

**Comment by aennen** [comment]
Same here, any updates ?

**Comment by carlosdiaz** [comment]
I solved part of this doing:
`pip3 install neo4j
Collecting neo4j`
which is not part of the requirements.txt, ResultError is still an issue
