### ISSUE TITLE
Not able to establish connection

### ISSUE THREAD

**Issue by prashanthkolaneru** [neo4j-examples/movies-python-bolt#43]
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by fbiville** [comment]
Hi, thanks for reporting, but this is far from being detailed enough.
When running locally, I noticed that the default `demo.neo4jlabs.com` environment has an expired certificate issue, so this might explain why it does not run?
I've pinged my colleagues about it, this will hopefully get fixed soon.

**Comment by fbiville** [comment]
Feel free to reopen the issue with more details if it persists.
