### ISSUE TITLE
Accessing graph database is slow

### ISSUE THREAD

**Issue by aytekincem** [neo4j-examples/movies-python-bolt#7]
Hello I find that creating couple of nodes and updating them takes around 5-6 seconds each time. Is it normal ? Are there any ways to improve the access to the database ?

**Comment by aytekincem** [comment]
I have upgraded my neo4j driver from 1.4 to 1.7 now it seems that the problem is solved, all queries run very fast. However only delete operation takes little bit time.

**Comment by jexp** [comment]
You might need to batch huge delete operations. And make sure you have a fast enough disk.
